apiVersion: autoscaling/v1

kind: HorizontalPodAutoscaler

metadata:
  name: hpa

spec:
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment