apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.appDeploymentName1 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appPod.appPodName }}
      app.kubernetes.io/version: {{ quote .Values.appPod.appPodVersion1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: {{ .Values.appPod.appPodName }}
      labels:
        app.kubernetes.io/name: {{ .Values.appPod.appPodName }}
        app.kubernetes.io/version: {{ quote .Values.appPod.appPodVersion1 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Values.appContainer.appContainerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag1 }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          requests:
            cpu: 100m
            memory: 16M
          limits:
            memory: 32M
          env:
          - name: BGG_DB_HOST
            value: "bgg-db-svc.{{ .Values.namespace }}.svc.cluster.local"
          - name: APP_PORT
            value: "3000"
          ports:
          - name: app-port1
            containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.deployment.appDeploymentName2 }}
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appPod.appPodName }}
      app.kubernetes.io/version: {{ quote .Values.appPod.appPodVersion2 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: {{ .Values.appPod.appPodName }}
      labels:
        app.kubernetes.io/name: {{ .Values.appPod.appPodName }}
        app.kubernetes.io/version: {{ quote .Values.appPod.appPodVersion2 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ .Values.appContainer.appContainerName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag2 }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: 100m
            memory: 16M
          limits:
            memory: 32M
        env:
        - name: BGG_DB_HOST
          value: "bgg-db-svc.{{ .Values.namespace }}.svc.cluster.local"
        - name: APP_PORT
          value: "3000"
        ports:
        - name: app-port2
          containerPort: 3000
