apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.svcName1 }}
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.appPod.appPodName }}
    #app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ quote .Values.appPod.appPodVersion1 }}
  ports:
  - name: {{ .Values.service.svcName1 }}
    port: {{ .Values.service.svcPort1 }}
    targetPort: {{ .Values.service.svcTargetPortName1 }}
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.svcName2 }}
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.appPod.appPodName }}
    #app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ quote .Values.appPod.appPodVersion2 }}
  ports:
  - name: {{ .Values.service.svcPortName2 }}
    port: {{ .Values.service.svcPort2 }}
    targetPort: {{ .Values.service.svcTargetPortName2 }}
    protocol: TCP