apiVersion: apps/v1
kind: Deployment

metadata:
  name: database-deployment
  namespace: myns3

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: database-pod
      app.kubernetes.io/version: "v1"
  template:
    metadata:
      name: database-pod
      labels:
        app.kubernetes.io/name: database-pod
        app.kubernetes.io/version: "v1"
    spec:
      containers:
      - name: database-container
        image: stackupiss/bgg-db:v1
        imagePullPolicy: Always
        ports:
        - name: database-port
          containerPort: 3306
---
apiVersion: v1
kind: Service

metadata:
  name: bgg-db-svc
  namespace: myns3

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: database-pod
  ports:
  #targetPort is the port in the container  
  - name: mysql-port-svc
    port: 3306
    targetPort: database-port